Importing libraries and the dataset: 

In [2]:
import pandas as pd

df = pd.read_csv('train.csv')
print(f"The shape of the dataset is: {df.shape}")
df.head()

The shape of the dataset is: (20800, 5)


id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

Dropping all the rows with NaN values, and creating a new dataframe called messages:

In [4]:
df=df.dropna(how='all',axis=0)

In [5]:
messages=df.copy()

In [6]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [7]:
messages.head()


id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

Adding a column called 'content', which will have all the information used for the model to get trained.

In [8]:
df['content'] = df['author']+' '+df['title']

In [9]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1      Ever get the feeling your life circles the rou...      0   
2      Why the Truth Might Get You Fired October 29, ...      1   
3      Videos 15 Civilians Killed In Single US Airstr...      1   
4      Print \nAn Iranian woman has been sentenced to...      1   
...                                                  ...    ...   
20795  Rapper T. I. unloaded on black celebrities who...      0   
20796  When the Green Bay Packers lost to the Washing...      0   
20797  The Macy’s of today grew from the union of sev...      0   
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1   
20799    David Swanson is an author, activist, journa...      1   

                                                 content  
0      Darrell Lucus House Dem Aide: We Didn’t Even S...  
1      Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...  
2      Consortiumnews.com Why the Truth Might Get You...  
3      Jessica Purkiss 15 Civilians Killed In Single ...  
4      Howard Portnoy Iranian woman jailed for fictio...  
...                                                  ...  
20795  Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...  
20796  Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...  
20797  Michael J. de la Merced and Rachel Abrams Macy...  
20798  Alex Ansary NATO, Russia To Hold Parallel Exer...  
20799            David Swanson What Keeps the F-35 Alive  

[20800 rows x 6 columns]

In [10]:
print(df['content'])

0        Darrell Lucus House Dem Aide: We Didn’t Even S...
1        Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2        Consortiumnews.com Why the Truth Might Get You...
3        Jessica Purkiss 15 Civilians Killed In Single ...
4        Howard Portnoy Iranian woman jailed for fictio...
                               ...                        
20795    Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796    Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...
20797    Michael J. de la Merced and Rachel Abrams Macy...
20798    Alex Ansary NATO, Russia To Hold Parallel Exer...
20799              David Swanson What Keeps the F-35 Alive
Name: content, Length: 20800, dtype: object


In [57]:
df['content'][1]

'Daniel J. Flynn FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

Separating the independent and dependent features: 

In [11]:
# Get the Independent Features
X=df.drop('label',axis=1)

# Get the Dependent features
Y=df['label']

In [12]:
Y.value_counts()

label
1    10413
0    10387
Name: count, dtype: int64

In [13]:
messages = df

In [14]:
import re
import nltk

nltk.download('stopwords')
nltk.download('punkt') 
nltk.download('wordnet') 

from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91968\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91968\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\91968\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Performing text processing: for 'title' column in the 'messages' dataFrame by removing non-alphanumeric characters, converting to lowercase, splitting into words, applying stemming, removing stopwords, and then joining the processed words back into a string. The resulting strings are stored in a list called 'corpus'.

In [15]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z0-9]',' ', str(messages['title'][i]))
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Text preprocessing pipeline using the NLTK library

The below code Iterates through the 'content' column of the 'messages' DataFrame, cleans each text entry by removing non-alphanumeric characters, converting to lowercase, and lemmatizing words while excluding stopwords:

In [16]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

cleaned_corpus = []
for i in range(len(messages)):
    review = re.sub('[^a-zA-Z0-9]',' ',str(messages['content'][i]))
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    cleaned_corpus.append(review)

In [17]:
cleaned_corpus[1]

'daniel j flynn flynn hillary clinton big woman campus breitbart'

In [56]:
cleaned_corpus

['darrell lucus house dem aide even see comey letter jason chaffetz tweeted',
 'daniel j flynn flynn hillary clinton big woman campus breitbart',
 'consortiumnews com truth might get fired',
 'jessica purkiss 15 civilian killed single u airstrike identified',
 'howard portnoy iranian woman jailed fictional unpublished story woman stoned death adultery',
 'daniel nussbaum jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'nan',
 'alissa j rubin beno hamon win french socialist party presidential nomination new york time',
 'nan',
 'megan twohey scott shane back channel plan ukraine russia courtesy trump associate new york time',
 'aaron klein obama organizing action partner soros linked indivisible disrupt trump agenda',
 'chris tomlinson bbc comedy sketch real housewife isi cause outrage',
 'amando flavio russian researcher discover secret nazi military base treasure hunter arctic photo',
 'jason ditz u official see link trump ru

Removing empty sentences from the corpus:

In [18]:
cleaned_corpus_ = [i for i in cleaned_corpus if i]
len(cleaned_corpus_)

20771

Similarly Dropping Those rows in Y w.r.t Corpus which were empty Strings

In [19]:
Y = df[list(map(lambda x: len(x)>0,cleaned_corpus))]
Y = Y['label']

Doing one-hot encoding:

In [20]:
voc_size=5000

In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in cleaned_corpus_]
onehot_repr

[[2461, 2654, 2643, 3179, 17, 4074, 3587, 4439, 4823, 3390, 1020, 2286],
 [516, 1552, 693, 693, 3034, 3574, 401, 882, 2991, 4573],
 [3173, 2873, 3159, 3778, 2360, 3669],
 [365, 3633, 3748, 4054, 4675, 1111, 1274, 4032, 3946],
 [2368, 3420, 3703, 882, 673, 1750, 4110, 761, 882, 4857, 3266, 1572],
 [516,
  38,
  3620,
  1804,
  515,
  4542,
  2847,
  3957,
  4668,
  627,
  959,
  69,
  3803,
  2413,
  2344,
  3361,
  4573],
 [958],
 [2065,
  1552,
  3531,
  935,
  1782,
  438,
  3977,
  3214,
  3796,
  4156,
  4363,
  3882,
  2244,
  4583],
 [958],
 [2077,
  3027,
  4743,
  3344,
  237,
  1129,
  1040,
  4074,
  1489,
  3025,
  3957,
  3148,
  3882,
  2244,
  4583],
 [3623, 4870, 1580, 4918, 3501, 3273, 4998, 1822, 2154, 4422, 3957, 1946],
 [4055, 1351, 3017, 4827, 1193, 3687, 681, 1701, 3978, 654],
 [450, 2667, 166, 1170, 3745, 857, 2435, 2621, 4446, 3745, 1719, 4795, 1946],
 [3390, 4453, 1274, 4601, 3587, 4906, 3957, 1489],
 [3395, 2111, 1812, 4820, 3343, 111, 4613, 2328, 687, 1802],
 

In [23]:
cleaned_corpus_[2]

'consortiumnews com truth might get fired'

In [24]:
# Finding the Max_len & Min_len of the Sentences w.r.t Cleaned_Corpus

def max_minlen(cleaned_corpus_):
  max_l = float('-inf')
  min_l = float('inf')
  for i in cleaned_corpus_:
    if len(i.split())>max_l:
      max_l = len(i.split())
    if len(i.split())<min_l:
      min_l = len(i.split())
  return max_l,min_l # max_l & min_l
max_minlen(cleaned_corpus_)

(51, 1)

In [25]:
onehot_repr[2]

[3173, 2873, 3159, 3778, 2360, 3669]

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [27]:
# setting max sent length: 
sent_length=40 
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) # Pre - adding zeros at the beg
print(embedded_docs)

[[   0    0    0 ... 3390 1020 2286]
 [   0    0    0 ...  882 2991 4573]
 [   0    0    0 ... 3778 2360 3669]
 ...
 [   0    0    0 ... 3882 2244 4583]
 [   0    0    0 ...   53 2684  501]
 [   0    0    0 ... 3667 2078 3268]]


In [28]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,  516, 1552,  693,
        693, 3034, 3574,  401,  882, 2991, 4573])

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0, 2461, 2654, 2643, 3179,   17,
       4074, 3587, 4439, 4823, 3390, 1020, 2286])

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [31]:
# setting max sent length
embedding_vector_features=50 
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

# setting 100 Neurons for Hyper-Parameter for LSTM
model.add(LSTM(100)) 

# Output Layer
model.add(Dense(1,activation='sigmoid')) 
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy']) # Compiling the model

In [32]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 50)            250000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 310,501
Trainable params: 310,501
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
len(embedded_docs),Y.shape

(20771, (20771,))

In [34]:
import numpy as np
X_final=np.array(embedded_docs)
Y_final=np.array(Y)

In [35]:
X_final.shape,Y_final.shape

((20771, 40), (20771,))

In [36]:
# Train & Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, Y_final, test_size=0.30, random_state=0)

In [37]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=20)

Epoch 1/5
727/727 [==============================] - 58s 77ms/step - loss: 0.1270 - accuracy: 0.9512 - val_loss: 0.0587 - val_accuracy: 0.9819
Epoch 2/5
727/727 [==============================] - 50s 68ms/step - loss: 0.0197 - accuracy: 0.9950 - val_loss: 0.0400 - val_accuracy: 0.9880
Epoch 3/5
727/727 [==============================] - 44s 61ms/step - loss: 0.0112 - accuracy: 0.9975 - val_loss: 0.0476 - val_accuracy: 0.9886
Epoch 4/5
727/727 [==============================] - 45s 62ms/step - loss: 0.0088 - accuracy: 0.9983 - val_loss: 0.0458 - val_accuracy: 0.9892
Epoch 5/5
727/727 [==============================] - 48s 66ms/step - loss: 0.0074 - accuracy: 0.9986 - val_loss: 0.0489 - val_accuracy: 0.9884


In [38]:
import tensorflow as tf
callback = tf.keras.callbacks.EarlyStopping(patience=4, mode='min', restore_best_weights=True) # Early Stopping

In [40]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=20,callbacks=[callback])

Epoch 1/5
727/727 [==============================] - 44s 61ms/step - loss: 0.0069 - accuracy: 0.9987 - val_loss: 0.0622 - val_accuracy: 0.9891
Epoch 2/5
727/727 [==============================] - 50s 68ms/step - loss: 0.0064 - accuracy: 0.9990 - val_loss: 0.0649 - val_accuracy: 0.9897
Epoch 3/5
727/727 [==============================] - 47s 65ms/step - loss: 0.0061 - accuracy: 0.9990 - val_loss: 0.0629 - val_accuracy: 0.9901
Epoch 4/5
727/727 [==============================] - 48s 66ms/step - loss: 0.0062 - accuracy: 0.9990 - val_loss: 0.0650 - val_accuracy: 0.9897
Epoch 5/5
727/727 [==============================] - 62s 85ms/step - loss: 0.0063 - accuracy: 0.9990 - val_loss: 0.0657 - val_accuracy: 0.9896


In [41]:
y_pred=model.predict(X_test)

195/195 [==============================] - 4s 16ms/step


In [42]:
y_pred=np.where(y_pred > 0.5, 1,0)

In [43]:
if (y_pred[0]==0):
  print(f'The News is Realiable & labelled as {y_pred[0]} and in real it is {y_test[0]}')
else:
  print(f'The News is Fake & labelled as {y_pred[0]} and in real it is {[y_test[0]]}')

The News is Fake & labelled as [1] and in real it is [1]


In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3110,   44],
       [  24, 3054]], dtype=int64)

In [45]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9890885750962772

Accuracy achieved using LSTM: 98%

Using Bidirectional LSTM

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Bidirectional

In [47]:
# creating a model:

embedding_vector_features=50
model2=Sequential()
model2.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model2.add(Bidirectional(LSTM(100))) # 100 Neurons Forward & Backward
# model2.add(Dropout(0.3)) # Model Tuning
model2.add(Dense(1,activation='sigmoid'))
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [48]:
print(model2.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 40, 50)            250000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              120800    
 l)                                                              
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 371,001
Trainable params: 371,001
Non-trainable params: 0
_________________________________________________________________
None


In [50]:
model2.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=20)

Epoch 1/5
727/727 [==============================] - 78s 107ms/step - loss: 0.1272 - accuracy: 0.9465 - val_loss: 0.0398 - val_accuracy: 0.9892
Epoch 2/5
727/727 [==============================] - 84s 116ms/step - loss: 0.0182 - accuracy: 0.9959 - val_loss: 0.0355 - val_accuracy: 0.9907
Epoch 3/5
727/727 [==============================] - 120s 165ms/step - loss: 0.0112 - accuracy: 0.9975 - val_loss: 0.0473 - val_accuracy: 0.9894
Epoch 4/5
727/727 [==============================] - 109s 150ms/step - loss: 0.0094 - accuracy: 0.9984 - val_loss: 0.0481 - val_accuracy: 0.9894
Epoch 5/5
727/727 [==============================] - 88s 121ms/step - loss: 0.0117 - accuracy: 0.9977 - val_loss: 0.0558 - val_accuracy: 0.9883


In [51]:
y_pred2= model2.predict(X_test)

195/195 [==============================] - 10s 28ms/step


In [52]:
y_pred2=np.where(y_pred2 > 0.5, 1,0)

In [53]:
print(confusion_matrix(y_test,y_pred2))

[[3125   29]
 [  44 3034]]


In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.9882862644415917

Accuracy achieved using Bidirectional LSTM: 98.8%

In [59]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3154
           1       0.99      0.99      0.99      3078

    accuracy                           0.99      6232
   macro avg       0.99      0.99      0.99      6232
weighted avg       0.99      0.99      0.99      6232



In [58]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3154
           1       0.99      0.99      0.99      3078

    accuracy                           0.99      6232
   macro avg       0.99      0.99      0.99      6232
weighted avg       0.99      0.99      0.99      6232

